### ISSUE TITLE
Change update frequency to 15 minutes

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [PiotrMachowski/Home-Assistant-custom-components-TGE#1]
Price table gets updated once per day, updating it every minute is ~pointless.
Refreshing it at HA start and then every 15 minutes seems sufficient.

**Comment by PiotrMachowski** [comment]
Actually it is already refreshed every 1h:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-TGE/blob/master/custom_components/tge/update_coordinator.py#L28
