### ISSUE TITLE
adding support for Python Holidays lib for Jinja

### ISSUE THREAD

**Issue by szczepuz999** [PiotrMachowski/Home-Assistant-custom-components-TGE#11]
At the moment we are able to use Jinja to write script which determines the distribution fees at week days and weekends. But we are unable to check if today is public holiday or not. Or am I wrong? 
I have G13 Tauron tariff and today whole day we have offpeak prices. But in my home assistant now are peak prices

**Comment by szczepuz999** [comment]
of course the workaround would be to calculate the prices in NodeRed with help of this integration https://www.home-assistant.io/integrations/workday/, but with Jinja script it would be much cleaner solution :)

**Comment by PiotrMachowski** [comment]
You can just use workday sensor inside the Jinja template, you definitely don't need to use NodeRed
