### ISSUE TITLE
Tomorrow prices still loading...

### ISSUE THREAD

**Issue by Mice30** [PiotrMachowski/Home-Assistant-custom-components-TGE#13]
Hi,
I am unable to preview (still Loading) Tomorrow prices in Apex Cards (today prices are fine).
- Core 2024.12.4
- Supervisor 2024.12.0
- Operating System 14.0
- Frontend 20241127.8
- TGE Installed by HACS preferred way. 

![image](https://github.com/user-attachments/assets/3592369e-0f1d-4130-80ac-e2d571fe09ec)

**Comment by PiotrMachowski** [comment]
As you can see [on the TGE](https://tge.pl/energia-elektryczna-rdn) prices for tomorrow haven't been published yet. They are published at 14:00

**Comment by Mice30** [comment]
Upss:). Thx!
