### ISSUE TITLE
Request to Add "Tomorrow" Prices to Entity Attributes

### ISSUE THREAD

**Issue by home409ca** [PiotrMachowski/Home-Assistant-custom-components-TGE#3]
Could you please add "Tomorrow" prices to the entity's attributes, just like how "prices_today" is currently set up? It would really help with planning ahead for energy usage.

**Comment by PiotrMachowski** [comment]
TGE doesn't provide such data on their website

**Comment by home409ca** [comment]
![image](https://github.com/user-attachments/assets/168a34de-22c6-46a9-aa37-a8313b892b4a)
You are wrong. Data for tomorrow is available after 1:30 PM when the stock market closes. Below is the proof. The data is for August 29. Today is August 28.

**Comment by PiotrMachowski** [comment]
Ok, I have missed that part. In such case most probably current behavior of the integration is incorrect

**Comment by PiotrMachowski** [comment]
Adjusted in v1.0.1
